services:
  jimdo.printer_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\PrinterEntityFilter
    arguments:
      - @jimdo.printer_entity_repository

  jimdo.ticket_date_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketDateFilter

  jimdo.ticket_id_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketIdFilter

  jimdo.template_ticket_filter_chain:
    class: Jimdo\JimkanbanBundle\Lib\Filter\FilterChain
    calls:
      - [add, [@jimdo.ticket_type_entity_filter, 'type' ]]
      - [add, [@jimdo.ticket_date_filter, 'created' ]]
      - [add, [@jimdo.ticket_id_filter, 'id' ]]
