services:
  zend.cache.google_auth:
    class: Zend\Cache\Storage\Adapter\Filesystem
    factory_class: Zend\Cache\StorageFactory
    factory_method: factory
    arguments:
      - {adapter: {name:'Filesystem', options: {ttl: 180}}}

  jimdo.google.client.gcp:
    class: Jimdo\JimkanbanBundle\Lib\Google\GoogleClient
    arguments:
      - @buzz
      - %gcp.email%
      - %gcp.password%
      - 'cloudprint'

  jimdo.google.authmanagerclient.gcp:
    class: Jimdo\JimkanbanBundle\Lib\Google\GoogleClientAuthManagerWrapper
    arguments:
      - @jimdo.google.client.gcp
      - @zend.cache.google_auth

  jimdo.gcp.client:
    class: Jimdo\JimkanbanBundle\Lib\Google\GCP\GCPClient
    arguments:
      - @jimdo.google.authmanagerclient.gcp
