services:
  jimdo.ticket_type_entity_repository:
    class:            Jimdo\JimkanbanBundle\Entity\TicketTypeRepository
    factory_service:  doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - 'JimdoJimkanbanBundle:TicketType'

  jimdo.printer_entity_repository:
    class:            Jimdo\JimkanbanBundle\Entity\PrinterRepository
    factory_service:  doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - 'JimdoJimkanbanBundle:Printer'


  jimdo.ticket_type_entity_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketTypeEntityFilter
    arguments:
      - @jimdo.ticket_type_entity_repository
