services:
  jimdo.template_data_view:
    class: Jimdo\JimkanbanBundle\Lib\TemplateData
    arguments:
      - @request
      - @jimdo.template_ticket_filter_chain
    scope: request

  jimdo.template_data_view_printers:
    class: Jimdo\JimkanbanBundle\Lib\TemplateDataView
    arguments:
      - @request
      - @jimdo.template_ticket_filter_chain
      - @jimdo.printing.provider.gcp
    scope: request
