print_buttons:
    pattern:  /iframe.html
    defaults: { _controller: "JimdoJimkanbanBundle:PrintButtons:show" }

print_buttons_loader_js:
    pattern:  /loader.js
    defaults: { _controller: "JimdoJimkanbanBundle:PrintButtons:js" }