template:
    pattern:  /view/ticket/
    defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:ticket" }

template_print_view:
    pattern:  /printview/ticket/
    defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:ticketprint" }

template_print:
    pattern:  /print/ticket/
    defaults: { _controller: "JimdoJimkanbanBundle:Print:printticket" }