template_ticket:
  pattern:  /ticket.html
  defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:ticket" }
  requirements:
      _method:  GET

template_ticket_print:
  pattern:  /print/ticket.paper
  defaults: { _controller: "JimdoJimkanbanBundle:Print:printticket" }
  requirements:
      _method:  POST

template_story:
    pattern:  /story.html
    defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:story" }
    requirements:
      _method:  GET

template_story_print:
  pattern:  /story.paper
  defaults: { _controller: "JimdoJimkanbanBundle:Print:printstory" }
  requirements:
    _method:  POST
