template:
    pattern:  /view/ticket/
    defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:ticket" }

template_print:
    pattern:  /print/ticket/
    defaults: { _controller: "JimdoJimkanbanBundle:TemplateView:printticket" }