JimdoJimkanbanBundle_tickettype:
  resource: "@JimdoJimkanbanBundle/Resources/config/routing/tickettype.yml"
  prefix:   /admin/tickettype

JimdoJimkanbanBundle_printer_config:
  resource: "@JimdoJimkanbanBundle/Resources/config/routing/printer.yml"
  prefix:   /admin/printer

JimdoJimkanbanBundle_template:
  resource: "@JimdoJimkanbanBundle/Resources/config/routing/template.yml"
  prefix:   /template

JimdoJimkanbanBundle_print:
  resource: "@JimdoJimkanbanBundle/Resources/config/routing/print.yml"
  prefix:   /print
