services:
  jimdo.ticket_type_entity_repository:
    class:            Jimdo\JimkanbanBundle\Entity\TicketTypeRepository
    factory_service:  doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - 'JimdoJimkanbanBundle:TicketType'

  jimdo.ticket_type_entity_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketTypeEntityFilter
    arguments:
      - @jimdo.ticket_type_entity_repository

  jimdo.ticket_date_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketDateFilter

  jimdo.template_ticket_filter_chain:
    class: Jimdo\JimkanbanBundle\Lib\Filter\FilterChain
    calls:
      - [add, [@jimdo.ticket_type_entity_filter, 'type' ]]
      - [add, [@jimdo.ticket_date_filter, 'created' ]]

  jimdo.template_data:
    class: Jimdo\JimkanbanBundle\Lib\TemplateData
    arguments:
      - @request
      - @jimdo.template_ticket_filter_chain
    scope: request