services:
  jimdo.ticket_type_entity_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketTypeEntityFilter
    arguments:
      - @doctrine.orm.default_entity_manager

  jimdo.ticket_date_filter:
    class: Jimdo\JimkanbanBundle\Lib\Filter\Templates\TicketDateFilter

  jimdo.ticket_filter_chain:
    class: Jimdo\JimkanbanBundle\Lib\Filter\FilterChain
    arguments:
      - @jimdo.ticket_date_filter
      - @jimdo.ticket_type_entity_filter
    calls:
      - [add, [@jimdo.ticket_type_entity_filter, 'type' ]]
      - [add, [@jimdo.ticket_date_filter, 'created' ]]
