imports:
    - { resource: "services/repositories.yml" }
    - { resource: "services/filters.yml" }
    - { resource: "services/listener.yml" }
    - { resource: "services/printing.yml" }
    - { resource: "services/google.yml" }

services:
  jimdo.template_data_view:
    class: Jimdo\JimkanbanBundle\Lib\TemplateDataView
    arguments:
      - @request
      - @jimdo.template_ticket_filter_chain
      - @jimdo.gcp.client
    scope: request
